# Generated by Django 5.0.2 on 2024-02-20 13:35

import Comptoire.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codif', models.CharField(max_length=10)),
                ('disignation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='S_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codif', models.CharField(max_length=10)),
                ('disignation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='S_famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codif', models.CharField(max_length=10)),
                ('disignation', models.CharField(max_length=50)),
                ('id_famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.famille', verbose_name='id')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codif', models.CharField(max_length=10)),
                ('disignation', models.CharField(max_length=50)),
                ('P_achat', models.FloatField()),
                ('P_vente', models.FloatField()),
                ('P_min', models.FloatField()),
                ('barcode', models.CharField(max_length=13, unique=True, validators=[Comptoire.models.validate_barcode])),
                ('fournisseur_best', models.IntegerField()),
                ('id_S_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.s_article', verbose_name='id')),
                ('id_S_famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.s_famille', verbose_name='id')),
            ],
        ),
    ]
