# Generated by Django 5.0.2 on 2024-02-20 13:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comptoire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='P_vente',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
        migrations.AlterField(
            model_name='article',
            name='id_S_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.s_article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id_S_famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.s_famille'),
        ),
        migrations.AlterField(
            model_name='s_famille',
            name='id_famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Comptoire.famille'),
        ),
    ]
